### ISSUE TITLE
Application crashes on startup after adding America/Los_Angeles on 10.11.1

### ISSUE THREAD

**Issue by ankurcha** [Abhishaker17/Clocker#1] opened 2015-11-15 05:00 UTC
Sounded nice but doesn't work on El Capitan 10.11.1 when I tried adding 'America/Los_Angeles' as one of the clocks.

console logs show this:

```
14/11/2015 20:55:38.088 lsd[255]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
14/11/2015 20:55:40.034 Clocker[47726]: *** -[NSCalendar component:fromDate:]: date cannot be nil
14/11/2015 20:55:40.040 Clocker[47726]: (
	0   CoreFoundation                      0x00007fff987afe32 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff95c1bdd4 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff98786b5c -[NSCalendar component:fromDate:] + 316
	3   Clocker                             0x00000001062b678e Clocker + 26510
	4   Clocker                             0x00000001062b6924 Clocker + 26916
	5   Clocker                             0x00000001062b61e3 Clocker + 25059
	6   AppKit                              0x00007fff9a76cd54 -[NSTableView(NSTableViewViewBased) makeViewForTableColumn:row:] + 76
	7   AppKit                              0x00007fff9a76c76d -[NSTableRowData _addViewToRowView:atColumn:row:] + 283
	8   AppKit                              0x00007fff9a76c4c6 -[NSTableRowData _addViewsToRowView:atRow:] + 184
	9   AppKit                              0x00007fff9a76acdf -[NSTableRowData _initializeRowView:atRow:] + 390
	10  AppKit                              0x00007fff9a76943f -[NSTableRowData _addRowViewForVisibleRow:withPriorView:] + 416
	11  AppKit                              0x00007fff9a7691d3 -[NSTableRowData _addRowViewForVisibleRow:withPriorRowIndex:inDictionary:withRowAnimation:] + 299
	12  AppKit                              0x00007fff9a767f99 -[NSTableRowData _unsafeUpdateVisibleRowEntries] + 1697
	13  AppKit                              0x00007fff9a76785a -[NSTableRowData updateVisibleRowViews] + 233
	14  AppKit                              0x00007fff9a7671d3 -[NSTableView layout] + 178
	15  AppKit                              0x00007fff9a7060df -[NSView _doLayout] + 53
	16  AppKit                              0x00007fff9a705d97 -[NSView _layoutSubtreeWithOldSize:] + 324
	17  AppKit                              0x00007fff9a705ff3 -[NSView _layoutSubtreeWithOldSize:] + 928
	18  AppKit                              0x00007fff9a67819b -[NSView setFrameSize:] + 1727
	19  AppKit                              0x00007fff9a69f620 -[NSClipView setFrameSize:] + 390
	20  AppKit                              0x00007fff9a6905b5 -[NSView setFrame:] + 476
	21  AppKit                              0x00007fff9a63829b -[NSScrollView _setContentViewFrame:] + 633
	22  AppKit                              0x00007fff9a635fd3 -[NSScrollView tile] + 2563
	23  AppKit                              0x00007fff9a635547 -[NSScrollView _tileWithoutRecursing] + 51
	24  AppKit                              0x00007fff9a6a21fb -[NSScrollView _update] + 27
	25  AppKit                              0x00007fff9a69ef42 NSViewLevelLayout + 165
	26  AppKit                              0x00007fff9a69ee87 -[NSView layout] + 14
	27  AppKit                              0x00007fff9a74a660 -[NSScrollView layout] + 56
	28  AppKit                              0x00007fff9a7060df -[NSView _doLayout] + 53
	29  AppKit                              0x00007fff9a705d97 -[NSView _layoutSubtreeWithOldSize:] + 324
	30  AppKit                              0x00007fff9a67819b -[NSView setFrameSize:] + 1727
	31  AppKit                              0x00007fff9a71f416 -[NSScrollView setFrameSize:] + 1147
	32  AppKit                              0x00007fff9a6905b5 -[NSView setFrame:] + 476
	33  AppKit                              0x00007fff9a69cbd5 -[NSView resizeWithOldSuperviewSize:] + 409
	34  AppKit                              0x00007fff9a69c569 -[NSView resizeSubviewsWithOldSize:] + 318
	35  AppKit                              0x00007fff9a69ef42 NSViewLevelLayout + 165
	36  AppKit                              0x00007fff9a69ee87 -[NSView layout] + 14
	37  AppKit                              0x00007fff9a7060df -[NSView _doLayout] + 53
	38  AppKit                              0x00007fff9a705d97 -[NSView _layoutSubtreeWithOldSize:] + 324
	39  AppKit                              0x00007fff9a67819b -[NSView setFrameSize:] + 1727
	40  AppKit                              0x00007fff9a6905b5 -[NSView setFrame:] + 476
	41  AppKit                              0x00007fff9a69cbd5 -[NSView resizeWithOldSuperviewSize:] + 409
	42  AppKit                              0x00007fff9a69c569 -[NSView resizeSubviewsWithOldSize:] + 318
	43  AppKit                              0x00007fff9a6781b7 -[NSView setFrameSize:] + 1755
	44  AppKit                              0x00007fff9a80934b -[NSNextStepFrame setFrameSize:] + 201
	45  AppKit                              0x00007fff9a6905b5 -[NSView setFrame:] + 476
	46  AppKit                              0x00007fff9a69cedd -[NSView resizeWithOldSuperviewSize:] + 1185
	47  AppKit                              0x00007fff9a7052a0 -[NSView layoutSubtreeIfNeeded] + 902
	48  AppKit                              0x00007fff9a724be5 -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 82
	49  AppKit                              0x00007fff9a70b5e2 -[NSWindow _setFrame:updateBorderViewSize:] + 1059
	50  AppKit                              0x00007fff9a72403d -[NSWindow _oldPlaceWindow:] + 1075
	51  AppKit                              0x00007fff9a723426 -[NSWindow _setFrameCommon:display:stashSize:] + 2719
	52  AppKit                              0x00007fff9a722979 -[NSWindow _setFrame:display:allowImplicitAnimation:stashSize:] + 222
	53  AppKit                              0x00007fff9a722894 -[NSWindow setFrame:display:] + 67
	54  Clocker                             0x00000001062b5c1f Clocker + 23583
	55  Foundation                          0x00007fff8a715835 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 1049
	56  Foundation                          0x00007fff8a780ef7 _NSSetCharValueAndNotify + 268
	57  Clocker                             0x00000001062b77df Clocker + 30687
	58  libsystem_trace.dylib               0x00007fff8b934082 _os_activity_initiate + 75
	59  AppKit                              0x00007fff9a8bb811 -[NSApplication sendAction:to:from:] + 460
	60  Clocker                             0x00000001062b4f95 Clocker + 20373
	61  AppKit                              0x00007fff9ae1842d -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
	62  AppKit                              0x00007fff9ae19411 -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
	63  AppKit                              0x00007fff9a85eb8d -[NSWindow sendEvent:] + 517
	64  AppKit                              0x00007fff9ad27155 -[NSStatusBarWindow sendEvent:] + 281
	65  AppKit                              0x00007fff9a7deb27 -[NSApplication sendEvent:] + 2540
	66  AppKit                              0x00007fff9a645d9a -[NSApplication run] + 796
	67  AppKit                              0x00007fff9a60efbe NSApplicationMain + 1176
	68  libdyld.dylib                       0x00007fff8bd805ad start + 1
)
14/11/2015 20:55:40.059 com.apple.xpc.launchd[1]: (com.abhishek.Clocker.149152[47726]) Service exited due to signal: Illegal instruction: 4
14/11/2015 20:55:40.113 com.apple.xpc.launchd[1]: (com.apple.ReportCrash[47730]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
14/11/2015 20:55:40.537 ReportCrash[47730]: Saved crash report for Clocker[47726] version 1.0 (9) to /Users/username/Library/Logs/DiagnosticReports/Clocker_2015-11-14-205540_UserNames-MacBook-Pro.crash
```

**Comment by Abhishaker17** [comment] 2015-11-15 05:10
Thanks. Investigating.

**Comment by Abhishaker17** [comment] 2015-11-15 06:11
Hey, can you elaborate more on this issue. I am unable to reproduce this. From the console log, this should be happening when you click on the icon.
1. Did you add any number of clocks before adding Los Angeles?

**Comment by ankurcha** [comment] 2015-11-15 19:10
Yes that is correct. I added one clock and it crashed, then restarted the app with the console log and when I clicked on the icon, it crashed again and I copied the logs.

**Comment by Abhishaker17** [comment] 2015-11-15 19:14
Thanks for the reply. According to the crash logs, a NSCalendar method is causing the crash. Looking into it.

**Comment by Abhishaker17** [comment] 2015-11-15 19:30
Hey Ankur, I have added a new version under the Release section. Can you please use this updated version and check whether the problem exists? Thank you for your patience.

**Comment by Abhishaker17** [comment] 2015-12-05 20:13
Hey Ankur, the new version (1.1.2) solves this issue. You can update the app from the Mac App Store or build the project after downloading it. Closing this issue.

**Closed by Abhishaker17** 2015-12-05 20:13 UTC
Labels: bug
